version: "2"
services:
  mysql:
    image: mysql:5.7.17                       #使用mysql镜像
    environment:                              #设置数据库的环境变量
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "cjw"
      MYSQL_PASSWORD: "123456"
    ports:                                    # 提供的端口
      - "3306:3306"
    volumes:                                  # 添加一个mysql数据的数据卷
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
