version: '2'
services:
  # apache服务器,内置一个php, 其中版本可以定制
  apache:
    build:
      context: ./apache-php7.1/                     #引入dockerfile的目录
      dockerfile: Dockerfile                        #引入dockerfile的文件名
    ports:                                          # 对外开放端口
      - "8080:80"
      - "8801:443"
    volumes:
    # 挂载数据盘 (PHP的配置文件未挂载，因为变量的原因,但是dockerfile,已经是匿名挂载.)
        - apache-config:/etc/apache2/
        - /var/www/apache:/var/www/
        - apache-log:/var/log/apache2/

volumes:
  apache-log:                                       # apache的匿名数据卷
    driver: local
  apache-config:
    driver: local
  apache-php-config:
    driver: local
